# Generated by Django 5.2.1 on 2025-05-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kategoriSoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katSoal', to='main.kategorisoal')),
            ],
        ),
        migrations.CreateModel(
            name='JawabanSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunci', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='main.soal')),
            ],
        ),
    ]
