# Generated by Django 5.2.1 on 2025-05-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal',
            name='kategoriSoal',
        ),
        migrations.DeleteModel(
            name='JawabanSoal',
        ),
        migrations.DeleteModel(
            name='Soal',
        ),
    ]
